version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
      timezone: 'Europe/Rome'

    open-pull-requests-limit: 15
    versioning-strategy: 'increase-if-necessary'

    groups:
      next-major:
        patterns:
          - 'next'
        update-types:
          - 'major'

      react-major:
        patterns:
          - 'react'
          - 'react-dom'
        update-types:
          - 'major'

      next-minor-patch:
        patterns:
          - 'next'
          - 'eslint-config-next'
        update-types:
          - 'minor'
          - 'patch'

      react-minor-patch:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
        update-types:
          - 'minor'
          - 'patch'

      ui-libs:
        patterns:
          - 'react-icons'

      css-tooling:
        patterns:
          - 'autoprefixer'
          - 'tailwindcss'
          - 'postcss*'

      formatting:
        patterns:
          - 'prettier'

      node:
        patterns:
          - '@types/node'

    labels:
      - 'dependencies'
      - 'dependabot'

    commit-message:
      prefix: 'deps'
      include: 'scope'
